### ISSUE TITLE
Call for Talks and Travel Grant Application

### ISSUE THREAD

**Issue by hereismglee** [ocftw/ctfweb#25]
是否可以把以下兩個連結，加在一個比較顯眼的地方。例如Early Bird Ticket上方？
Call for Talks https://docs.google.com/forms/d/e/1FAIpQLScpVHtZvyTaCsVmkNtw4byEx-Jobb-vjkjtg5hSitVFHBochg/viewform?c=0&w=1 
Travel Grant Application https://docs.google.com/forms/d/e/1FAIpQLSf6Oq63xSQkDOCrMbYL4nOOfNT-4FfPc-dz4VcuLZyzxdwVrg/viewform?c=0&w=1

**Comment by poga** [comment]
![2017-05-04 20 53 30](https://cloud.githubusercontent.com/assets/8631/25704408/d8a283c2-310b-11e7-80cb-9925624200ce.png)

這樣如何？
