### ISSUE TITLE
og圖片

### ISSUE THREAD

**Issue by shulusama** [ocftw/ctfweb#26]
![og](https://cloud.githubusercontent.com/assets/7334450/25656186/5e6eccaa-302a-11e7-96bc-888b548a0a4b.png)

**Comment by poga** [comment]
fixed at https://github.com/ocftw/ctfweb/commit/2cb7fd70454893bf3e85db37ba446154be416f10

preview:

![2017-05-04 20 59 10](https://cloud.githubusercontent.com/assets/8631/25704570/8c49163e-310c-11e7-9142-dbf0f69a7191.png)
