### ISSUE TITLE
Call for Partners 都改成 Call for Talks 

### ISSUE THREAD

**Issue by lulukeng** [ocftw/ctfweb#28]
要改的部分包括：
1. 最上方功能選單，call for partners 改成 call for talks
2. 下面call for partners區塊 (tickets旁邊)，改成Call for Talks，說明文字包括：We invite individuals to submit abstracts or workshop / presentation proposals of no more than 300 words by Jun.16th 2017.

**Comment by poga** [comment]
下面 call for partners 改成 call for talks 後，連結也要改到 #27 提到的表單嗎？

（目前是 mailto:intl@ocf.tw）

**Comment by lulukeng** [comment]
是的，下面call for talks請連結到 #27的表單，感謝～～
另外，下方call for talks 中的"Contact Us" 下面文字(5/10到期5/20到期的這兩段)換掉，換成：Those selected for inclusion in the conference programme will be notified no later than 23rd June 2017.　The registration fee will be waived for individuals presenting.

**Comment by poga** [comment]
done~

https://github.com/ocftw/ctfweb/commit/a6b0246ec4fb88e74b4d6cc25fe86fd80b0bd9d9
