### ISSUE TITLE
First screen 要有活動日期

### ISSUE THREAD

**Issue by ttcat** [ocftw/ctfweb#30]

**Comment by ttcat** [comment]
手機會看不到

**Comment by poga** [comment]
fixed at https://github.com/ocftw/ctfweb/commit/7a423edc4c3d5aa3c3f45833e7ab668b6c76801a

![2017-05-23 00 43 52](https://cloud.githubusercontent.com/assets/8631/26319273/f721b3a6-3f50-11e7-8a65-9754c8abb6c9.png)
