### ISSUE TITLE
小數值調整

### ISSUE THREAD

**Issue by shulusama** [ocftw/ctfweb#5]
.ph3 {
    padding-left: 2rem;
    padding-right: 2rem;
}
.pv2 {
    padding-top: 0rem;
    padding-bottom: 0rem;
}
.mt4 {
    margin-top: 1rem;
}
.bg-white-90 {
    background-color: hsl(0, 0%, 100%);
}

**Comment by poga** [comment]
closed by https://github.com/ocftw/ctfweb/commit/6905334485602c702b12c58285b0d917ef0d2097
